[package]
name = "ketchup-core"
description = "Canonical core contracts for Ketchup"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ed25519-dalek = "2.2.0"
sha2 = "0.10.9"
tempfile = "3.23.0"

[lints]
workspace = true
