//! The command table: label key and tool of every `AppCommand`.

use crate::*;

impl CommandRegistry {
    pub(crate) const COMMANDS: [CommandSpec; 124] = [
        CommandSpec {
            id: AppCommand::New,
            label_key: "file-new",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Open,
            label_key: "file-open",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Save,
            label_key: "file-save",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SaveAs,
            label_key: "file-save-as",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ImportMeshStl,
            label_key: "file-import-stl",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ImportDrawingDxf,
            label_key: "file-import-dxf",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ImportExactStep,
            label_key: "file-import-step",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ImportExactIges,
            label_key: "file-import-iges",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ImportSketchupScene,
            label_key: "file-import-sketchup-scene",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ImportBlenderGlb,
            label_key: "file-import-blender-glb",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ConvertSelectedMeshToExact,
            label_key: "model-convert-mesh-exact",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportDrawingDxf,
            label_key: "file-export-dxf",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportExactStep,
            label_key: "file-export-exact",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportExactIges,
            label_key: "file-export-iges",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportMeshStl,
            label_key: "file-export-mesh",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportPrintThreeMf,
            label_key: "file-export-print-3mf",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportBlenderGlb,
            label_key: "file-export-blender-glb",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportGeneralFabrication,
            label_key: "file-export-general-fabrication",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportWeldmentCutList,
            label_key: "file-export-weldment-cut-list",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportSheetMetalManufacturing,
            label_key: "file-export-sheet-metal-manufacturing",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportHomagMpr,
            label_key: "file-export-homag-mpr",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ReviewCamExport,
            label_key: "file-review-cam-export",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ReviewStaticFea,
            label_key: "file-review-static-fea",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ReviewLocalPdm,
            label_key: "file-review-local-pdm",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ExportHundeggerBtlx,
            label_key: "file-export-hundegger-btlx",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Select,
            label_key: "tool-select",
            tool: Some(ActiveTool::Select),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Line,
            label_key: "tool-line",
            tool: Some(ActiveTool::Line),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Rectangle,
            label_key: "tool-rectangle",
            tool: Some(ActiveTool::Rectangle),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Circle,
            label_key: "tool-circle",
            tool: Some(ActiveTool::Circle),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Arc,
            label_key: "tool-arc",
            tool: Some(ActiveTool::Arc),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Polygon,
            label_key: "tool-polygon",
            tool: Some(ActiveTool::Polygon),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Ellipse,
            label_key: "tool-ellipse",
            tool: Some(ActiveTool::Ellipse),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SolidSubtract,
            label_key: "solid-tool-subtract",
            tool: Some(ActiveTool::SolidSubtract),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SolidTrim,
            label_key: "solid-tool-trim",
            tool: Some(ActiveTool::SolidTrim),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SolidUnion,
            label_key: "solid-tool-union",
            tool: Some(ActiveTool::SolidUnion),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SolidIntersect,
            label_key: "solid-tool-intersect",
            tool: Some(ActiveTool::SolidIntersect),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SolidSplit,
            label_key: "solid-tool-split",
            tool: Some(ActiveTool::SolidSplit),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::PlanarOffset,
            label_key: "feature-planar-offset",
            tool: Some(ActiveTool::PlanarOffset),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Helix,
            label_key: "feature-helix",
            tool: Some(ActiveTool::Helix),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Sweep,
            label_key: "feature-sweep",
            tool: Some(ActiveTool::Sweep),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Loft,
            label_key: "feature-loft",
            tool: Some(ActiveTool::Loft),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Revolve,
            label_key: "feature-revolve",
            tool: Some(ActiveTool::Revolve),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Shell,
            label_key: "feature-shell",
            tool: Some(ActiveTool::Shell),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Fillet,
            label_key: "feature-fillet",
            tool: Some(ActiveTool::Fillet),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Chamfer,
            label_key: "feature-chamfer",
            tool: Some(ActiveTool::Chamfer),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::PushPull,
            label_key: "tool-push-pull",
            tool: Some(ActiveTool::PushPull),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Move,
            label_key: "tool-move",
            tool: Some(ActiveTool::Move),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Rotate,
            label_key: "tool-rotate",
            tool: Some(ActiveTool::Rotate),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Scale,
            label_key: "tool-scale",
            tool: Some(ActiveTool::Scale),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Measure,
            label_key: "tool-measure",
            tool: Some(ActiveTool::Measure),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Orbit,
            label_key: "tool-orbit",
            tool: Some(ActiveTool::Orbit),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Pan,
            label_key: "tool-pan",
            tool: Some(ActiveTool::Pan),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Undo,
            label_key: "action-undo",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Redo,
            label_key: "action-redo",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Copy,
            label_key: "action-copy",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Cut,
            label_key: "action-cut",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Paste,
            label_key: "action-paste",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Duplicate,
            label_key: "action-duplicate",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Delete,
            label_key: "action-delete",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Deselect,
            label_key: "action-deselect",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SelectAll,
            label_key: "action-select-all",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::InvertSelection,
            label_key: "action-invert-selection",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Group,
            label_key: "model-group",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Ungroup,
            label_key: "model-ungroup",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::MakeComponent,
            label_key: "model-make-component",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::MakeUnique,
            label_key: "model-make-unique",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ReplaceComponent,
            label_key: "model-replace-component",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::SelectAllInstances,
            label_key: "model-select-all-instances",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::AssignTag,
            label_key: "model-assign-tag",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::AlignOccurrences,
            label_key: "model-align-occurrences",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::DistributeOccurrences,
            label_key: "model-distribute-occurrences",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::LinearPattern,
            label_key: "model-linear-pattern",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::RectangularPattern,
            label_key: "model-rectangular-pattern",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::CircularPattern,
            label_key: "model-circular-pattern",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::GroundOccurrence,
            label_key: "model-ground-occurrence",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::UngroundOccurrence,
            label_key: "model-unground-occurrence",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::RenameOccurrence,
            label_key: "model-rename-occurrence",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::RenameDefinition,
            label_key: "model-rename-definition",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::PurgeUnused,
            label_key: "model-purge-unused",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Hide,
            label_key: "model-hide",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::HideOthers,
            label_key: "model-hide-others",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Unhide,
            label_key: "model-unhide",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::UnhideAll,
            label_key: "model-unhide-all",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::PreviousView,
            label_key: "view-previous",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::HomeView,
            label_key: "view-home",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewIso,
            label_key: "view-iso",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewTop,
            label_key: "view-top",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewBottom,
            label_key: "view-bottom",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewFront,
            label_key: "view-front",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewBack,
            label_key: "view-back",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewRight,
            label_key: "view-right",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewLeft,
            label_key: "view-left",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::GridAxes),
            label_key: "view-grid-axes",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::WhiteBackground),
            label_key: "view-white-background",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Shadows),
            label_key: "view-shadows",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Fog),
            label_key: "view-fog",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::HiddenObjects),
            label_key: "view-hidden-objects",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Xray),
            label_key: "view-xray",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewShaded,
            label_key: "view-shaded",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Wireframe),
            label_key: "view-wireframe",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Monochrome),
            label_key: "view-monochrome",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::HiddenLine),
            label_key: "view-hidden-line",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Edges),
            label_key: "view-edges",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Profiles),
            label_key: "view-profiles",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Halos),
            label_key: "view-halos",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::DepthCue),
            label_key: "view-depth-cue",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::FadeDistantEdges),
            label_key: "view-fade-distant-edges",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::HighContrastEdges),
            label_key: "view-high-contrast-edges",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::SelectionHalo),
            label_key: "view-selection-halo",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Endpoints),
            label_key: "view-endpoints",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Midpoints),
            label_key: "view-midpoints",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Extensions),
            label_key: "view-extensions",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Jitter),
            label_key: "view-jitter",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::Dashes),
            label_key: "view-dashes",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::View(ViewFlag::ColorByAxis),
            label_key: "view-color-by-axis",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ViewProjection,
            label_key: "view-projection",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ZoomFit,
            label_key: "view-zoom-fit",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ZoomSelection,
            label_key: "view-zoom-selection",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::CenterSelection,
            label_key: "view-center-selection",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ZoomWindow,
            label_key: "view-zoom-window",
            tool: Some(ActiveTool::ZoomWindow),
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ZoomIn,
            label_key: "view-zoom-in",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::ZoomOut,
            label_key: "view-zoom-out",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::Shortcuts,
            label_key: "help-shortcuts",
            tool: None,
            implemented: true,
        },
        CommandSpec {
            id: AppCommand::About,
            label_key: "help-about",
            tool: None,
            implemented: true,
        },
    ];

    pub(crate) fn spec(id: AppCommand) -> &'static CommandSpec {
        Self::COMMANDS
            .iter()
            .find(|command| command.id == id)
            .expect("every application command is registered")
    }
}
