[package]
name = "ketchup-interaction"
description = "Exact spatial queries and canonical preview interactions for Ketchup"
version.workspace = true
edition.workspace = true
autotests = false
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ketchup-model = { path = "../ketchup-model" }
ketchup-geometry = { path = "../ketchup-geometry" }

[lints]
workspace = true

[dev-dependencies]
ketchup-model = { path = "../ketchup-model", features = ["testing"] }

[[test]]
name = "integration"
path = "tests/integration.rs"
